### ISSUE TITLE
Is there a way to add track speed?

### ISSUE THREAD

**Issue by Loleirs** [hmxmilohax/rb-patches#4]
Sorry if this is the wrong place but
as the title say, i was wondering if its possible since Lego rb and rb1 are slow in terms of track speed.

Thanks in advance <3

**Comment by lunalawl** [comment]
It's on the table, i initially wasn't going to as some people consider it "invalid" but i've since come to my senses lol

**Comment by lunalawl** [comment]
Added in https://github.com/hmxmilohax/rb-patches/commit/390bae583d6499e2ab3372f63f0b3acf1e488fbf
